### ISSUE TITLE
Enh: Add option to search all lists in the domain (project) in Advanced Search

### ISSUE THREAD

**Issue by bindul** [apache/incubator-ponymail#430] opened 2018-01-14 06:01 UTC
On lists.apache.org , when using the regular search (top menu), you can choose to search _This list_ or _All tlp.apache.org lists_. However, if you try to use the _Advanced_ search, your only options to _Look in_ are  _Current list_ and _All lists_. The latter of course searches all lists in the archive (across TLPs). It would be nice to be able to use advanced search on all lists in a TLP.

So, this request is to add a third option for the _Look in_ field for all lists in the _Current TLP_ or _Current domain_ (or whatever you want to call it).

**Comment by sebbASF** [comment] 2018-05-14 09:46
This is a duplicate of #131

**Closed by sebbASF** 2018-05-14 09:46 UTC
Labels: enhancement
