### ISSUE TITLE
Serach does not return existing results

### ISSUE THREAD

**Issue by rvernica** [apache/incubator-ponymail#548] opened 2021-08-01 09:26 UTC
If I set a search filter with _Less than 1 month ago_ I get six results:
https://lists.apache.org/list.html?dev@arrow.apache.org:lte=1M:copy
![image](https://user-images.githubusercontent.com/241185/127766057-113ce8b0-985a-4da2-b341-8838332bb454.png)
If I set the filter with _Less than 1 year ago_ I get *no results*:
https://lists.apache.org/list.html?dev@arrow.apache.org:lte=1y:copy
![image](https://user-images.githubusercontent.com/241185/127766074-1ba3901e-e15b-48de-82d3-f2dd9e75f95c.png)

**Comment by Humbedooh** [comment] 2021-08-01 09:35
I've tried this with and without authenticating, and I get 253 emails in both cases.
Can you share the stats.lua URL that gets called during your search? It should be available in your browser inspector tool (shift+ctrl+i)

**Comment by Humbedooh** [comment] 2021-08-01 09:37
Does the same thing happen with the next gen interface? ( https://lists.apache.org/x/list.html?dev@arrow.apache.org:lte=1y:copy )

**Comment by sebbASF** [comment] 2021-08-01 14:06
I've also tried it and I get 253 results (at present: the number will likely change as time moves on).

The screenshot does not show the full URL: are you sure there is nothing else after the 'lte=' that could be causing the search to fail? For example the following returns nothing:

https://lists.apache.org/list.html?dev@arrow.apache.org:lte=1y:copyy

**Comment by rvernica** [comment] 2021-08-01 15:58
The screenshots corresponds to the URL included before the screenshot.

Now the 1y filter seems to work as expected. Maybe it is a transient issue. The next get UI works as well.

I've seen this issue before but only got to report it now. I'll report back if I see this again.

**Comment by Humbedooh** [comment] 2021-08-03 10:56
Closing as Cannot Reproduce for now. If the error occurs again, we'll take another look.

**Closed by Humbedooh** 2021-08-03 10:56 UTC
